env:
  browser: true
  commonjs: true
  es2021: true
globals:
  process: true
extends: standard
parserOptions:
  ecmaVersion: latest
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  eol-last:
    - error
    - never