version: '3.8'
services:
  mongo:
    container_name: uranus-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  redis:
    container_name: uranus-redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis:/data

volumes:
  mongo:
  redis: