const {
  APP_NAME,
  NODE_ENV,
  PORT,
  HOST,
  MONGO_URI,
  SESSION_SECRET,
  PBKDF2_KEYLEN,
  PBKDF2_ITERATION,
  PBKDF2_DIGEST,
  AWS_S3_BUCKET,
  AWS_S3_ACCESS_KEY,
  AWS_S3_SECRET,
  AWS_S3_REGION,
  AWS_S3_DOMAIN
} = process.env;

const AppConfig = {
  APP_NAME,
  NODE_ENV,
  PORT,
  HOST,
  MONGO_URI,
  SESSION_SECRET,
  PBKDF2_KEYLEN: Number(PBKDF2_KEYLEN),
  PBKDF2_ITERATION: Number(PBKDF2_ITERATION),
  PBKDF2_DIGEST,
  isDev: NODE_ENV !== 'production',
  AWS_S3_BUCKET,
  AWS_S3_ACCESS_KEY,
  AWS_S3_SECRET,
  AWS_S3_REGION,
  AWS_S3_DOMAIN
};

module.exports = {
  AppConfig
};